modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://gitlab.com/LaDestitute/Spelunkcraft/-/issues"
license="All rights reserved."
[[mods]]
modId = "jadestuff"
version = "0.1"
displayName = "Spelunkcraft"
logoFile="icon.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/spelunkcraft"
authors = "LaDestitute"
credits = "All contributors and testers"
description = '''A mod that brings Spelunky to Minecraft!'''